WhoWantToBeAMillionaire/Areas/Admin/Controllers/QuestionAdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WhoWantToBeAMillionaire.Data;
using WhoWantToBeAMillionaire.Models;

namespace WhoWantToBeAMillionaire.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class QuestionAdminController : Controller
    {
        private readonly DataContext _dataContext;
        public QuestionAdminController(DataContext context)
        {
            _dataContext = context;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _dataContext.Questions.OrderByDescending(p => p.Id).Include(p=>p.Topic).ToListAsync());
        }
        public IActionResult Create(int? roomId)
        {
            ViewBag.Topics = new SelectList(_dataContext.Topics, "Id", "Name");
            if (roomId.HasValue)
            {
                ViewBag.RoomId = roomId.Value;
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(QuestionModel question, int? roomId)
        {
            ViewBag.Topics = new SelectList(_dataContext.Topics, "Id", "Name", question.TopicId);
            if (ModelState.IsValid)
            {
                if (roomId.HasValue)
                {
                    question.RoomId = roomId.Value;
                }

                _dataContext.Add(question);
                await _dataContext.SaveChangesAsync();
                TempData["success"] = "Add Question Success!";
                return RedirectToAction("Details", "RoomAdmin", new { id = roomId });
            }
            else
            {
                TempData["error"] = "Model Error!!!";
                List<string> errors = new List<string>();
                foreach (var value in ModelState.Values)
                {
                    foreach (var error in value.Errors)
                    {
                        errors.Add(error.ErrorMessage);
                    }
                }
                string errorMessage = string.Join("\n", errors);
                return BadRequest(errorMessage);
            }

            return View(question);
        }

        public async Task<IActionResult> Edit(int Id, int? roomId)
        {
            QuestionModel question = await _dataContext.Questions.FirstOrDefaultAsync(p => p.Id == Id);
            ViewBag.Topics = new SelectList(_dataContext.Topics, "Id", "Name");
            if (roomId.HasValue)
            {
                ViewBag.RoomId = roomId.Value;
            }
            return View(question);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int Id, QuestionModel question, int? roomId)
        {
            ViewBag.Topics = new SelectList(_dataContext.Topics, "Id", "Name", question.TopicId);

            var existed_question = _dataContext.Questions.Find(Id);
            if (ModelState.IsValid)
            {
                //Update
                existed_question.Content = question.Content;
                existed_question.CorrectAnswer = question.CorrectAnswer;
                existed_question.Wrong_1 = question.Wrong_1;
                existed_question.Wrong_3 = question.Wrong_3;
                existed_question.Wrong_2 = question.Wrong_2;
                existed_question.Difficulty = question.Difficulty;
                existed_question.TopicId = question.TopicId;
                //

                _dataContext.Update(existed_question);
                await _dataContext.SaveChangesAsync();
                TempData["success"] = "Update Question Success!";
                return RedirectToAction("Details", "RoomAdmin", new { id = roomId });
                
            }
            else
            {
                TempData["error"] = "Model Error!!!";
                List<string> errors = new List<string>();
                foreach (var value in ModelState.Values)
                {
                    foreach (var error in value.Errors)
                    {
                        errors.Add(error.ErrorMessage);
                    }
                }
                string errorMessage = string.Join("\n", errors);
                return BadRequest(errorMessage);
            }

            return View(question);
        }

        public async Task<IActionResult> Delete(int Id, int? roomId)
        {
            QuestionModel question = await _dataContext.Questions.FirstOrDefaultAsync(p => p.Id == Id);

            if (question == null)
            {
                return NotFound();
            }
            
            _dataContext.Questions.Remove(question);
            await _dataContext.SaveChangesAsync();
            TempData["success"] = "Delete Question Success";
            return RedirectToAction("Details", "RoomAdmin", new { id = roomId });
        }
    }
}

WhoWantToBeAMillionaire/Controllers/GameController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.DotNet.MSIdentity.Shared;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using WhoWantToBeAMillionaire.Data;
using WhoWantToBeAMillionaire.Models;

namespace WhoWantToBeAMillionaire.Controllers
{
    public class GameController : Controller
    {
        public readonly DataContext _dataContext;

        public GameController(DataContext dataContext)
        {
            _dataContext = dataContext;
        }

        public List<QuestionModel> GetQuestions(int? roomId = null)
        {
            List<QuestionModel> questions = new List<QuestionModel>();
            if (roomId == null)
            {
                questions = _dataContext.Questions
                                        .ToList();
                return questions;
            }
            else
            {
                questions = _dataContext.Questions
                                        .Where(q => q.RoomId == roomId)
                                        .ToList();
            }

            var easyQuestions = questions
                                .Where(q => q.Difficulty == 1) // Mức độ dễ
                                .OrderBy(q => Guid.NewGuid()) // Random
                                .Take(5) // Lấy 5 câu
                                .ToList();

            var mediumQuestions = questions
                                  .Where(q => q.Difficulty == 2) // Mức độ trung bình
                                  .OrderBy(q => Guid.NewGuid())
                                  .Take(5)
                                  .ToList();

            var hardQuestions = questions
                                .Where(q => q.Difficulty == 3) // Mức độ khó
                                .OrderBy(q => Guid.NewGuid())
                                .Take(5)
                                .ToList();

            var allQuestions = easyQuestions
                               .Concat(mediumQuestions)
                               .Concat(hardQuestions)
                               .ToList();
            return allQuestions;
        }

        public IActionResult StartGame()
        {
            return View();
        }

        [HttpPost]
        public IActionResult StartGame(string play, string roomCode = "")
        {
            int roomId = 1;
            List<QuestionModel> questions = new List<QuestionModel>();
            if (play == "rand")
            {
                questions = GetQuestions();
            }
            else
            {
                var room = _dataContext.Rooms
                                       .FirstOrDefault(q => q.RoomCode == roomCode);
                if (room == null)
                {
                    TempData["notice"] = "*mã phòng không đúng!";
                    return View();
                }
                questions = GetQuestions(room.Id);
                roomId = room.Id;
            }
            // Lưu danh sách câu hỏi vào Session
            HttpContext.Session.Set("Questions", questions);
            HttpContext.Session.SetInt32("CurrentQuestionIndex", 0);
            HttpContext.Session.SetInt32("Score", 0);
            HttpContext.Session.SetInt32("Reward", 0);
            HttpContext.Session.SetInt32("RoomId", roomId);
            // Lưu thời gian bắt đầu
            HttpContext.Session.Set("StartTime", DateTime.Now);

            return RedirectToAction("Question");
        }

        public async Task<IActionResult> EndGame()
        {
            // Lấy dữ liệu từ Session
            var score = HttpContext.Session.GetInt32("Score") ?? 0;
            var reward = HttpContext.Session.GetInt32("Reward") ?? 0;
            var roomId = HttpContext.Session.GetInt32("RoomId") ?? 0;
            var currentLevel = HttpContext.Session.GetInt32("CurrentQuestionIndex") ?? 1;
            var startTime = HttpContext.Session.Get<DateTime>("StartTime");
            var endTime = DateTime.Now;

            // Tính toán thời gian hoàn thành
            var duration = endTime - startTime;

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if(userId != null && roomId != 1)
            {

                var gameHistory = new HistoryModel
                {
                    UserId = userId,
                    RoomId = roomId,
                    PlayedAt = startTime,
                    Score = score,
                    Reward = reward,
                    Completed = true,
                    Duration = duration
                };

                _dataContext.Histories.Add(gameHistory);
                await _dataContext.SaveChangesAsync();
            }

            ViewBag.Score = score;
            ViewBag.Reward = reward;

            return View();
        }

        public IActionResult DataQuestion()
        {
            var questions = HttpContext.Session.Get<List<QuestionModel>>("Questions");
            var currentIndex = HttpContext.Session.GetInt32("CurrentQuestionIndex") ?? 0;

            //if (currentIndex >= questions.Count)
            //{

            //}

            var currentQuestion = questions[currentIndex];
            currentQuestion.ShuffleAnswers(); // Trộn câu trả lời

            if (currentQuestion != null)
            {
                var question = new
                {
                    index = currentIndex,
                    Content = currentQuestion.Content,
                    answer1 = currentQuestion.ShuffledAnswers[0],
                    answer2 = currentQuestion.ShuffledAnswers[1],
                    answer3 = currentQuestion.ShuffledAnswers[2],
                    answer4 = currentQuestion.ShuffledAnswers[3]
                };

                return Ok(question);
            }
            else
            {
                return BadRequest();
            }
        }

        public IActionResult CheckAnswer(string selectedAnswer)
        {
            var questions = HttpContext.Session.Get<List<QuestionModel>>("Questions");
            var currentIndex = HttpContext.Session.GetInt32("CurrentQuestionIndex") ?? 0;
            var score = HttpContext.Session.GetInt32("Score") ?? 0;
            var reward = HttpContext.Session.GetInt32("Reward") ?? 0;

            var currentQuestion = questions[currentIndex];

            if (currentQuestion.CorrectAnswer == selectedAnswer)
            {
                score++;
                HttpContext.Session.SetInt32("Score", score);
                //Tinh tien thuong
                if (currentIndex > 10)
                {
                    reward += CalculateReward(currentIndex);
                }
                else
                {
                    reward = CalculateReward(currentIndex);
                }
                HttpContext.Session.SetInt32("Reward", reward);

                if (currentIndex + 1 >= questions.Count)
                {
                    return Json("End");
                }
                else
                { 
                    currentIndex++;
                    HttpContext.Session.SetInt32("CurrentQuestionIndex", currentIndex);
                }
            }
            else
            {
                if (currentIndex > 5)
                {
                    if (currentIndex > 10)
                        // Nếu trên mức 10, tính thưởng dựa trên câu cuối cùng trả lời đúng
                        score = currentIndex-1;
                    else
                        score = 5;
                        reward = CalculateReward(5);
                }
                else
                {
                    // Nếu chưa qua mức 10, lấy điểm của mốc an toàn
                    score = 0;
                    reward = 0;
                }
                HttpContext.Session.SetInt32("Reward", reward);
                HttpContext.Session.SetInt32("Score", score);
                return Json("Wrong");
            }

            return Json("Correct"); // Hiển thị câu hỏi tiếp theo
        }

        public IActionResult Question()
        {

            return View();
        }

        public IActionResult FiftyFifty()
        {
            var questions = HttpContext.Session.Get<List<QuestionModel>>("Questions");
            var currentIndex = HttpContext.Session.GetInt32("CurrentQuestionIndex") ?? 0;
            var currentQuestion = questions[currentIndex];
            currentQuestion.ShuffleAnswers(); // Trộn câu trả lời

            // Tìm hai đáp án sai
            var wrongAnswers = currentQuestion.ShuffledAnswers
                                              .Where(answer => answer != currentQuestion.CorrectAnswer)
                                              .Take(2)
                                              .ToList();

            return Json(wrongAnswers); // Trả về 2 đáp án sai đã chọn
        }

        public IActionResult AskAudience()
        {
            var questions = HttpContext.Session.Get<List<QuestionModel>>("Questions");
            var currentIndex = HttpContext.Session.GetInt32("CurrentQuestionIndex") ?? 0;
            var currentQuestion = questions[currentIndex];

            // Xác định câu trả lời đúng
            string correctAnswer = currentQuestion.CorrectAnswer;

            // Tạo phần trăm ngẫu nhiên cho các đáp án
            Random random = new Random();
            int correctPercent = random.Next(60, 90); // Xác suất cho đáp án đúng (60% - 90%)
            int remainingPercent = 100 - correctPercent;

            // Chia phần trăm còn lại cho các đáp án sai
            int wrongPercent1 = random.Next(0, remainingPercent);
            int wrongPercent2 = random.Next(0, remainingPercent - wrongPercent1);
            int wrongPercent3 = remainingPercent - wrongPercent1 - wrongPercent2;

            // Tạo danh sách kết quả
            var results = new List<object>
            {

WhoWantToBeAMillionaire/Areas/Admin/Views/RoomAdmin/Create.cshtml
@model RoomModel
<div class="container">
    <div class="page-title">
        <h3>Create</h3>
    </div>
    <div class="row">

        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">Create Room</div>
                <div class="card-body">
                    <h5 class="card-title"></h5>
                    <form class="form-horizontal" asp-action="Create" method="post" enctype="multipart/form-data">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group row">
                            <label asp-for="Name" class="col-sm-2">Name</label>
                            <div class="col-sm-10">
                                <input asp-for="Name" type="text" class="form-control">
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="line"></div><br>
                        <div class="form-group row">
                            <div class="col-sm-4 offset-sm-2">
                                <a asp-action="Index" asp-controller="RoomAdmin" class="btn btn-secondary mb-2"><i class="fas fa-times"></i> Cancel</a>
                                <button type="submit" class="btn btn-primary mb-2"><i class="fas fa-save"></i> Save</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

WhoWantToBeAMillionaire/Areas/Admin/Views/RoomAdmin/Details.cshtml
@model RoomModel

<h2>Chi Tiết Phòng</h2>

<div>
    <h4>Tên phòng: @Model.Name</h4>
    <h4>Chủ phòng: @ViewBag.HostName</h4>
    <p><strong>Mã Phòng:</strong> @Model.RoomCode</p>
    <p><strong>Thời Gian Tạo:</strong> @Model.CreatedAt.ToString("g")</p>
</div>

<a asp-action="Index" class="btn btn-secondary">Quay Lại</a>
@if (ViewBag.IsHost || ViewBag.IsAdmin)
{
    @if (Model.IsActive)
    {
        <span class="badge bg-success">Công khai</span>
    }
    else
    {
        <span class="badge bg-secondary">Riêng tư</span>
    }
    <form asp-action="ToggleRoomStatus" method="post">
        <input type="hidden" name="id" value="@Model.Id" />
        <button type="submit" class="btn btn-sm @(!Model.IsActive ? "btn-success" : "btn-secondary")">
            @(!Model.IsActive ? "Convert to Public" : "Convert to Private")
        </button>
    </form>
    <a onclick="return confirm('Are u sure to delete?')" asp-action="Delete" class="btn btn-danger btn-sm confirmDeletion" asp-controller="RoomAdmin" asp-route-Id="@Model.Id">Xóa phòng</a>
}
<div class="container">
    <div class="row">
        @if (ViewBag.IsHost || ViewBag.IsAdmin)
        {
            <div class="col-md-12 col-lg-12">
                <div class="card">
                    <div class="card-header">
                        Questions
                        <a asp-action="Create" asp-controller="QuestionAdmin" asp-route-roomId="@Model.Id" class="btn btn-success">Create Question</a>
                    </div>
                    <div class="card-body">
                        <p class="card-title"></p>
                        <table class="table table-hover" id="dataTables-example" width="100%">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Content</th>
                                    <th>CorrectAnswer</th>
                                    <th>Wrong_1</th>
                                    <th>Wrong_2</th>
                                    <th>Wrong_3</th>
                                    <th>Difficulty</th>
                                    <th>Topic</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in ViewBag.Questions)
                                {
                                    <tr>
                                        <td>@item.Id</td>
                                        <td>@item.Content</td>
                                        <td>@item.CorrectAnswer</td>
                                        <td>@item.Wrong_1</td>
                                        <td>@item.Wrong_2</td>
                                        <td>@item.Wrong_3</td>
                                        <td>
                                            @if (item.Difficulty == 1)
                                            {
                                                <span class="text text-success">Easy</span>
                                            }
                                            else if (item.Difficulty == 2)
                                            {
                                                <span class="text text-warning">Medium</span>
                                            }
                                            else
                                            {
                                                <span class="text text-danger">Difficulty</span>
                                            }
                                        </td>
                                        <td>
                                            @item.Topic.Name
                                        </td>
                                        <td>
                                            <a asp-action="Edit" class="btn btn-warning btn-sm" asp-controller="QuestionAdmin" asp-route-roomId="@Model.Id" asp-route-Id="@item.Id">Edit</a>
                                            <a onclick="return confirm('Are u sure to delete?')" asp-action="Delete" class="btn btn-danger btn-sm confirmDeletion" asp-controller="QuestionAdmin" asp-route-roomId="@Model.Id" asp-route-Id="@item.Id">Delete</a>
                                        </td>
                                    </tr>
                                }

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        }
        
        <div class="col-md-12 col-lg-12">
            <div class="card">
                <div class="card-header">
                    History
                </div>
                <div class="card-body">
                    <p class="card-title"></p>
                    <table class="table table-hover" id="dataTables-example" width="100%">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>User</th>
                                <th>Room Code</th>
                                <th>Played At</th>
                                <th>Score</th>
                                <th>Duration</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in ViewBag.Historys)
                            {
                                <tr>
                                    <td>@item.Id</td>
                                    <td>@item.User.Name</td>
                                    <td>@item.Room.RoomCode</td>
                                    <td>@item.PlayedAt</td>
                                    <td>@item.Score</td>
                                    <td>@item.Duration</td>
                                    <td>
                                        @* <a asp-action="Edit" class="btn btn-warning btn-sm" asp-controller="QuestionAdmin" asp-route-Id="@item.Id">Edit</a>
                                        <a onclick="return confirm('Are u sure to delete?')" asp-action="Delete" class="btn btn-danger btn-sm confirmDeletion" asp-controller="QuestionAdmin" asp-route-Id="@item.Id">Delete</a> *@
                                    </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-12 col-lg-12">
            <div class="card">
                <div class="card-header">
                    Leader board
                </div>
                <div class="card-body">
                    <p class="card-title"></p>
                    <table class="table table-hover" id="dataTables-example" width="100%">
                        <thead>
                            <tr>
                                <th>Rank</th>
                                <th>Player Name</th>
                                <th>High Score</th>
                                <th>Best Duration</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (ViewBag.Leaderboard != null)
                            {
                                int rank = 1;
                                foreach (var player in ViewBag.Leaderboard)
                                {
                                    <tr>
                                        <td>@rank</td>
                                        <td>@player.UserName</td>
                                        <td>@player.MaxScore</td>
                                        <td>@player.BestDuration.ToString("hh\\:mm\\:ss")</td>
                                    </tr>
                                    rank++;
                                }
                            }
                            

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

WhoWantToBeAMillionaire/Areas/Admin/Views/RoomAdmin/Index.cshtml
@model IEnumerable<RoomModel>

<div class="container">
    <div class="row">
        <div class="col-md-12 col-lg-12">
            <div class="card">
                <div class="card-header">
                    Your Rooms
                    <a asp-action="Create" asp-controller="RoomAdmin" class="btn btn-success">Create Room</a>
                </div>
                <div class="card-body">
                    <p class="card-title"></p>
                    <table class="table table-hover" id="dataTables-example" width="100%">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Host Name</th>
                                <th>Room Name</th>
                                <th>RoomCode</th>
                                <th>CreatedAt</th>
                                <th>IsActive</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in ViewBag.UserRooms)
                            {
                                <tr>
                                    <td>@item.Id</td>
                                    <td>@item.HostPlayer.Name</td>
                                    <td>@item.Name</td>
                                    <td>@item.RoomCode</td>
                                    <td>@item.CreatedAt.ToString("g")</td>
                                    <td>@item.IsActive</td>
                                    <td>
                                        <a asp-action="Details" class="btn btn-warning btn-sm" asp-controller="RoomAdmin" asp-route-Id="@item.Id">Manage</a>
                                        <a asp-area="default" asp-controller="Game" asp-action="StartGame" asp-route-roomId="@item.Id" class="btn btn-primary">Start Game</a>
                                    </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 col-lg-12">
            <div class="card">
                <div class="card-header">
                    All Rooms
                </div>
                <div class="card-body">
                    <p class="card-title"></p>
                    <table class="table table-hover" id="dataTables-example" width="100%">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Host Name</th>
                                <th>Room Name</th>
                                <th>RoomCode</th>
                                <th>CreatedAt</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                @if (item.IsActive == true)
                                {
                                    <tr>
                                        <td>@item.Id</td>
                                        <td>@item.HostPlayer.Name</td>
                                        <td>@item.Name</td>
                                        <td>@item.RoomCode</td>
                                        <td>@item.CreatedAt.ToString("g")</td>
                                        <td>
                                            <a asp-action="Details" class="btn btn-warning btn-sm" asp-controller="RoomAdmin" asp-route-Id="@item.Id">Manage</a>
                                            <a asp-area="default" asp-controller="Game" asp-action="StartGame" asp-route-roomId="@item.Id" class="btn btn-primary">Start Game</a>
                                        </td>
                                    </tr>
                                }
                                else if (item.IsActive == false && (User.IsInRole("Admin") || User.Identity.Name == item.HostPlayer.UserName))
                                {
                                    <tr>
                                        <td>@item.Id</td>
                                        <td>@item.HostPlayer.Name</td>
                                        <td>@item.Name</td>
                                        <td>@item.RoomCode</td>
                                        <td>@item.CreatedAt.ToString("g")</td>
                                        <td>
                                            <a asp-action="Details" class="btn btn-warning btn-sm" asp-controller="RoomAdmin" asp-route-Id="@item.Id">Manage</a>
                                            <a asp-area="default" asp-controller="Game" asp-action="StartGame" asp-route-roomId="@item.Id" class="btn btn-primary">Start Game</a>
                                        </td>
                                    </tr>
                                }
                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>