WhoWantToBeAMillionaire/Areas/Admin/Controllers/AccountAdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WhoWantToBeAMillionaire.Data;
using WhoWantToBeAMillionaire.Models.ViewModels;
using WhoWantToBeAMillionaire.Models;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Hosting;

namespace WhoWantToBeAMillionaire.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AccountAdminController : Controller
    {
        private UserManager<AppUserModel> _userManage;
        private SignInManager<AppUserModel> _signInManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly DataContext _dataContext;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public AccountAdminController(IWebHostEnvironment webHostEnvironment,RoleManager<IdentityRole> roleManager, SignInManager<AppUserModel> signInManager, UserManager<AppUserModel> userManage, DataContext dataContext)
        {
            _userManage = userManage;
            _signInManager = signInManager;
            _dataContext = dataContext;
            _roleManager = roleManager;
            _webHostEnvironment = webHostEnvironment;
        }
        public async Task<IActionResult> Index()
        {
            var user = await _userManage.GetUserAsync(User);

            var history = await _dataContext.Histories.Include(p => p.Room).Include(p => p.User).Where(p=>p.UserId==user.Id).ToListAsync();
            ViewBag.Historys = history;

            return View(user);
        }

        public IActionResult Login(string returnUrl)
        {
            return View(new LoginViewModel { ReturnUrl = returnUrl });
        }
        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginViewModel loginVM)
        {
            if (ModelState.IsValid)
            {
                Microsoft.AspNetCore.Identity.SignInResult result = await _signInManager.PasswordSignInAsync(loginVM.Username, loginVM.Password, false, false);
                if (result.Succeeded)
                {
                    TempData["success"] = "Đăng nhập thành công.";
                    return Redirect(loginVM.ReturnUrl ?? "/");

                }
                TempData["success"] = "Đăng nhập thất bại.";
                ModelState.AddModelError("", "Username hoặc Password không hợp lệ.!");
            }
            return View(loginVM);
        }

        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(RegisterViewModel user)
        {

            if (ModelState.IsValid)
            {
                var role = await _roleManager.FindByNameAsync("User");

                AppUserModel newUser = new AppUserModel { UserName = user.Username, Email = user.Email, RoleId = role.Id };
                IdentityResult result = await _userManage.CreateAsync(newUser, user.Password);

                var createUser = await _userManage.FindByEmailAsync(user.Email);


                await _userManage.AddToRoleAsync(createUser, role.Name);

                if (result.Succeeded)
                {
                    TempData["Success"] = "Đăng ký tài khoản thành công!";
                    return RedirectToAction("login");
                }
                foreach (IdentityError error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(user);
        }
        public async Task<IActionResult> Logout(string returnUrl = "/")
        {
            await _signInManager.SignOutAsync();
            return Redirect(returnUrl);
        }

        [HttpGet]
        public async Task<IActionResult> Profile(string id)
        {
            var user = await _userManage.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Profile(string id,AppUserModel usermodel)
        {
            var user = await _userManage.FindByIdAsync(id);

            if (ModelState.IsValid)
            {
                
                if (usermodel.ImageUpload != null)
                {
                    //upload new image
                    string uploadsDir = Path.Combine(_webHostEnvironment.WebRootPath, "images/users");
                    string imageName = Guid.NewGuid().ToString() + "_" + usermodel.ImageUpload.FileName;
                    string filePath = Path.Combine(uploadsDir, imageName);
                    //delete old picture
                    if(user.Image != null)
                    {
                        string oldfilePath = Path.Combine(uploadsDir, user.Image);

                        try
                        {

                            if (System.IO.File.Exists(oldfilePath))
                            {
                                System.IO.File.Delete(oldfilePath);
                            }

                        }
                        catch (Exception)
                        {
                            ModelState.AddModelError("", "An error occurred while deleting the product image.");
                        }
                    }
                    FileStream fs = new FileStream(filePath, FileMode.Create);
                    await usermodel.ImageUpload.CopyToAsync(fs);
                    fs.Close();
                    user.Image = imageName;
                }

                //hash the new pass
                user.PhoneNumber = usermodel.PhoneNumber;
                user.Name = usermodel.Name;

                await _userManage.UpdateAsync(user);
                return RedirectToAction("Index");
            }
            else
            {
                TempData["error"] = "Model đang có một vài thứ bị lỗi!!!";
                List<string> errors = new List<string>();
                foreach (var value in ModelState.Values)
                {
                    foreach (var error in value.Errors)
                    {
                        errors.Add(error.ErrorMessage);
                    }
                }
                string errorMessage = string.Join("\n", errors);
                return BadRequest(errorMessage);
            }
        }

    }
}

WhoWantToBeAMillionaire/Areas/Admin/Controllers/TopicAdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WhoWantToBeAMillionaire.Data;
using WhoWantToBeAMillionaire.Models;

namespace WhoWantToBeAMillionaire.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class TopicAdminController : Controller
    {
        private readonly DataContext _dataContext;
        public TopicAdminController(DataContext context)
        {
            _dataContext = context;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _dataContext.Topics.OrderByDescending(p => p.Id).ToListAsync());
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TopicModel topic)
        {
            if (ModelState.IsValid)
            {

                _dataContext.Add(topic);
                await _dataContext.SaveChangesAsync();
                TempData["success"] = "Add Topic Success!";
                return RedirectToAction(nameof(Index));
            }
            else
            {
                TempData["error"] = "Model Error!!!";
                List<string> errors = new List<string>();
                foreach (var value in ModelState.Values)
                {
                    foreach (var error in value.Errors)
                    {
                        errors.Add(error.ErrorMessage);
                    }
                }
                string errorMessage = string.Join("\n", errors);
                return BadRequest(errorMessage);
            }

            return View(topic);
        }

        public async Task<IActionResult> Edit(int Id)
        {
            TopicModel topic = await _dataContext.Topics.FirstOrDefaultAsync(p => p.Id == Id);
            return View(topic);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int Id, TopicModel topic)
        {

            var existed_topic = _dataContext.Topics.Find(topic.Id);
            if (ModelState.IsValid)
            {


                //Update
                existed_topic.Name = topic.Name;
                existed_topic.Status = topic.Status;
                //

                _dataContext.Update(existed_topic);
                await _dataContext.SaveChangesAsync();
                TempData["success"] = "Update Topic Success!";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["error"] = "Model Error!!!";
                List<string> errors = new List<string>();
                foreach (var value in ModelState.Values)
                {
                    foreach (var error in value.Errors)
                    {
                        errors.Add(error.ErrorMessage);
                    }
                }
                string errorMessage = string.Join("\n", errors);
                return BadRequest(errorMessage);
            }

            return View(topic);
        }

        public async Task<IActionResult> Delete(int Id)
        {
            TopicModel topic = await _dataContext.Topics.FirstOrDefaultAsync(p => p.Id == Id);

            if (topic == null)
            {
                return NotFound();
            }
            _dataContext.Topics.Remove(topic);
            await _dataContext.SaveChangesAsync();
            TempData["success"] = "Delete Topic Success";

            return RedirectToAction("Index");
        }
    }
}

WhoWantToBeAMillionaire/Areas/Admin/Views/Shared/_Layout.cshtml
<!doctype html>
<!--
* Bootstrap Simple Admin Template
* Version: 2.1
* Author: Alexis Luna
* Website: https://github.com/alexis-luna/bootstrap-simple-admin-template
-->
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Dashboard | Bootstrap Simple Admin Template</title>
    <link href="~/assets/vendor/fontawesome/css/fontawesome.min.css" rel="stylesheet">
    <link href="~/assets/vendor/fontawesome/css/solid.min.css" rel="stylesheet">
    <link href="~/assets/vendor/fontawesome/css/brands.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/datatables/datatables.min.css" rel="stylesheet">
    <link href="~/assets/css/master.css" rel="stylesheet">
    <link href="~/assets/vendor/chartsjs/Chart.min.css" rel="stylesheet">
    <link href="~/assets/vendor/flagiconcss/css/flag-icon.min.css" rel="stylesheet">
</head>

<body>
    <div class="wrapper">
        <nav id="sidebar" class="active">
            <div class="sidebar-header">
                <img src="~/assets/img/bootstraper-logo.png" alt="bootraper logo" class="app-logo">
            </div>
            <ul class="list-unstyled components text-secondary">
                <li>
                    <a asp-action="Index" asp-controller="Admin"><i class="fas fa-home"></i> Dashboard</a>
                </li>
                <li>
                    <a asp-action="Index" asp-controller="TopicAdmin"><i class="fas fa-table"></i> Topics</a>
                </li>
                <li>
                    <a asp-action="Index" asp-controller="RoomAdmin"><i class="fas fa-chart-bar"></i> Rooms</a>
                </li>
                <li>
                    <a href="icons.html"><i class="fas fa-icons"></i> Icons</a>
                </li>
                <li>
                    <a href="#uielementsmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle no-caret-down"><i class="fas fa-layer-group"></i> UI Elements</a>
                    <ul class="collapse list-unstyled" id="uielementsmenu">
                        <li>
                            <a href="ui-buttons.html"><i class="fas fa-angle-right"></i> Buttons</a>
                        </li>
                        <li>
                            <a href="ui-badges.html"><i class="fas fa-angle-right"></i> Badges</a>
                        </li>
                        <li>
                            <a href="ui-cards.html"><i class="fas fa-angle-right"></i> Cards</a>
                        </li>
                        <li>
                            <a href="ui-alerts.html"><i class="fas fa-angle-right"></i> Alerts</a>
                        </li>
                        <li>
                            <a href="ui-tabs.html"><i class="fas fa-angle-right"></i> Tabs</a>
                        </li>
                        <li>
                            <a href="ui-date-time-picker.html"><i class="fas fa-angle-right"></i> Date & Time Picker</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#authmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle no-caret-down"><i class="fas fa-user-shield"></i> Authentication</a>
                    <ul class="collapse list-unstyled" id="authmenu">
                        <li>
                            <a href="login.html"><i class="fas fa-lock"></i> Login</a>
                        </li>
                        <li>
                            <a href="signup.html"><i class="fas fa-user-plus"></i> Signup</a>
                        </li>
                        <li>
                            <a href="forgot-password.html"><i class="fas fa-user-lock"></i> Forgot password</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#pagesmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle no-caret-down"><i class="fas fa-copy"></i> Pages</a>
                    <ul class="collapse list-unstyled" id="pagesmenu">
                        <li>
                            <a href="blank.html"><i class="fas fa-file"></i> Blank page</a>
                        </li>
                        <li>
                            <a href="404.html"><i class="fas fa-info-circle"></i> 404 Error page</a>
                        </li>
                        <li>
                            <a href="500.html"><i class="fas fa-info-circle"></i> 500 Error page</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a asp-action="Index" asp-controller="UserAdmin"><i class="fas fa-user-friends"></i>Users</a>
                </li>
                <li>
                    <a href="settings.html"><i class="fas fa-cog"></i>Settings</a>
                </li>
            </ul>
        </nav>
        <div id="body" class="active">
            <nav class="navbar navbar-expand-lg navbar-white bg-white">
                <button type="button" id="sidebarCollapse" class="btn btn-light"><i class="fas fa-bars"></i><span></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="nav navbar-nav ml-auto">
                        <li class="nav-item" style="display:flex; align-items:center;">
                            <a asp-action="Index" asp-controller="Home" asp-area="default" class="nav-item text-secondary"><i class="fas fa-link"></i> <span>Game page</span></a>
                        </li>
@*                         <li class="nav-item dropdown">
                            <div class="nav-dropdown">
                                <a href="" class="nav-item nav-link dropdown-toggle text-secondary" data-toggle="dropdown"><i class="fas fa-link"></i> <span>Quick Access</span> <i style="font-size: .8em;" class="fas fa-caret-down"></i></a>
                                <div class="dropdown-menu dropdown-menu-right nav-link-menu">
                                    <ul class="nav-list">
                                        <li><a href="" class="dropdown-item"><i class="fas fa-list"></i> Access Logs</a></li>
                                        <div class="dropdown-divider"></div>
                                        <li><a href="" class="dropdown-item"><i class="fas fa-database"></i> Back ups</a></li>
                                        <div class="dropdown-divider"></div>
                                        <li><a href="" class="dropdown-item"><i class="fas fa-cloud-download-alt"></i> Updates</a></li>
                                        <div class="dropdown-divider"></div>
                                        <li><a href="" class="dropdown-item"><i class="fas fa-user-shield"></i> Roles</a></li>
                                    </ul>
                                </div>
                            </div>
                        </li> *@
                        <li class="nav-item dropdown">
                            <div class="nav-dropdown">
                                <a href="" class="nav-item nav-link dropdown-toggle text-secondary" data-toggle="dropdown"><i class="fas fa-user"></i> <span>John Doe</span> <i style="font-size: .8em;" class="fas fa-caret-down"></i></a>
                                <div class="dropdown-menu dropdown-menu-right nav-link-menu">
                                    <ul class="nav-list">
                                        <li><a asp-action="Index" asp-controller="AccountAdmin" class="dropdown-item"><i class="fas fa-address-card"></i> Profile</a></li>
                                        <li><a href="" class="dropdown-item"><i class="fas fa-envelope"></i> Messages</a></li>
                                        <li><a href="" class="dropdown-item"><i class="fas fa-cog"></i> Settings</a></li>
                                        <div class="dropdown-divider"></div>
                                        <li><a asp-action="Logout" asp-controller="AccountAdmin" class="dropdown-item"><i class="fas fa-sign-out-alt"></i> Logout</a></li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
            <div class="content">
                <partial name="_NotificationPartial" />
                @RenderBody()
            </div>
        </div>
    </div>
    <script src="~/assets/vendor/jquery/jquery.min.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/chartsjs/Chart.min.js"></script>
    <script src="~/assets/js/dashboard-charts.js"></script>
    <script src="~/assets/vendor/datatables/datatables.min.js"></script>
    <script src="~/assets/js/initiate-datatables.js"></script>
    <script src="~/assets/js/script.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>